feature/header
Maksym-Babich/News-app pull request #11
Opened 2023-02-19 18:57 UTC by OleksandrKochenko

created header markup and styles

2023-02-19 21:41 UTC, Maksym-Babich requested changes

2023-02-19 21:41 UTC, Maksym-Babich commented on src/images/sprite.svg
> +        <symbol id="moon" viewBox="0 0 32 32">
потрібно видалити зміни, там вже є нові іконки

2023-02-19 21:41 UTC, Maksym-Babich commented on src/partials/header.html
> +        <li class="main-nav-item"><a href="">Home</a></li>
пусті посилання, можна одразу додати посилання на сторінки

2023-02-19 21:41 UTC, Maksym-Babich commented on src/sass/_header.scss
> +.container {
класу контейнер не треба давати ніяких стилів бо вони вплинуть на усі інші секції, стилі можна дати частково хедеру, частково на ще один дів який обгорне контент у контейнері

2023-02-19 22:00 UTC, OleksandrKochenko commented on src/images/sprite.svg
> +        <symbol id="moon" viewBox="0 0 32 32">
Видалено

2023-02-19 22:15 UTC, OleksandrKochenko commented on src/partials/header.html
> +        <li class="main-nav-item"><a href="">Home</a></li>
додано

2023-02-19 22:16 UTC, OleksandrKochenko commented on src/sass/_header.scss
> +.container {
прибрав стилі з контейнера

2023-02-20 06:52 UTC, Maksym-Babich approved these changes

2023-02-20 06:53 UTC, merged